# Generated by Django 5.0.4 on 2024-04-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('imgpath', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('mpaarating', models.CharField(max_length=10)),
                ('userrating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
