# Generated by Django 5.0.4 on 2024-04-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imgpath',
            new_name='imgPath',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='mpaarating',
            new_name='mpaaRating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='userrating',
            new_name='userRating',
        ),
    ]
