# Generated by Django 5.0.4 on 2024-04-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0002_rename_imgpath_movie_imgpath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='mpaaRating',
        ),
        migrations.AddField(
            model_name='movie',
            name='label',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
